# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesurge < Formula
  desc "Surgical, zero-touch live diagnostic utility for hardened Kubernetes clusters."
  homepage "https://github.com/kubesurge/kubesurge"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_darwin_x86_64.tar.gz"
      sha256 "d4674ef1a961068e1aef7afdc959514102955b8f82aadae1b49caa636bb2ff35"

      define_method(:install) do
        bin.install "kubesurge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_darwin_arm64.tar.gz"
      sha256 "ba90bcf178fd0a92ca0b07d11103166c4fb3b103a0200318e0af73a67b5a7eeb"

      define_method(:install) do
        bin.install "kubesurge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_linux_x86_64.tar.gz"
      sha256 "78f2fe3fba5e2be9c9710270dd10abd8520fe9a649bc5fa3635b5daadd3e4b0b"
      define_method(:install) do
        bin.install "kubesurge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_linux_arm64.tar.gz"
      sha256 "f225b47533fe0af38383b60b40f5dd059d602820c449a672ab87fd12ed86dfd4"
      define_method(:install) do
        bin.install "kubesurge"
      end
    end
  end
end
