# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesurge < Formula
  desc "Surgical, zero-touch live diagnostic utility for hardened Kubernetes clusters."
  homepage "https://github.com/kubesurge/kubesurge"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_darwin_x86_64.tar.gz"
      sha256 "ff55aac56816a1d22191fec2f52cd449e1af56298548f8f272e85e879846f240"

      define_method(:install) do
        bin.install "kubesurge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_darwin_arm64.tar.gz"
      sha256 "fba8af642a4d6d04884e155e2e22c316a4fa5d3020a99035842892de49aa8196"

      define_method(:install) do
        bin.install "kubesurge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_linux_x86_64.tar.gz"
      sha256 "8ffb19566429c1f1285357042f1e0dd1ab47107d65fb0eee71bb88ea3e2ba2e7"
      define_method(:install) do
        bin.install "kubesurge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_linux_arm64.tar.gz"
      sha256 "341a6b2041e6f72e1d5830f7c9aba3e605942695848ee44feb94bd72202f4a71"
      define_method(:install) do
        bin.install "kubesurge"
      end
    end
  end
end
