# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubesurge < Formula
  desc "Surgical, zero-touch live diagnostic utility for hardened Kubernetes clusters."
  homepage "https://github.com/kubesurge/kubesurge"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_darwin_x86_64.tar.gz"
      sha256 "5f8465a5fca843739dfd97dfc841b7ecbde8be3f3dbcda7eb64b45319f5bca17"

      define_method(:install) do
        bin.install "kubesurge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_darwin_arm64.tar.gz"
      sha256 "6b5babf7f2a659f638e4e781e9653f978b31b263986886e0a65427015e1057c6"

      define_method(:install) do
        bin.install "kubesurge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_linux_x86_64.tar.gz"
      sha256 "f7d9e71a8f2a3f1af6b5ab9c4ac36d228cfb9f37389829210740a3561ed9c038"
      define_method(:install) do
        bin.install "kubesurge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubesurge/kubesurge/releases/download/v0.1.0/kubesurge_linux_arm64.tar.gz"
      sha256 "5d4a456388327a1ca2fecd748f86bbdb422e3d498ac7328fc01e5543bced8660"
      define_method(:install) do
        bin.install "kubesurge"
      end
    end
  end
end
